#!/bin/bash
REPO=$1
cd ~git/
if [ -d ${REPO} ]
  then echo "Repo already exists!"
  exit;
fi
mkdir -p ${REPO}
cd ${REPO}
cp ~/.gitignore .
git init --shared=all --template=/home/git/.git-nonbare-template
git add .gitignore
git commit -m'add .gitignore'
